In [2]:
print("hello world")

hello world


In [1]:
import sys
print("Python version:", sys.version)

Python version: 3.12.0 | packaged by Anaconda, Inc. | (main, Oct  2 2023, 17:29:18) [GCC 11.2.0]


In [1]:
import random as r 
import numpy as np


In [6]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [8]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
list = []
for i in range (25):
    list.append(r.randint(1,101))

#np.array(list)
print(list)


[52, 76, 4, 72, 21, 68, 78, 33, 99, 76, 2, 44, 81, 77, 40, 68, 67, 57, 7, 52, 98, 79, 75, 101, 74]


In [24]:
list = []
for i in range (25):
    list.append(r.randint(1,101))

array1=np.array(list).reshape(5,5)
print(array1)


[[ 38  11  80  71  90]
 [ 24  53   8  97  78]
 [ 46 100   8   8  78]
 [ 33  82  34  98  30]
 [ 52  53  90  56   7]]


In [ ]:
arr1=np.array([4,5,7,2,5])
arr2=np.array([55,68,69,67,76])
print(f"Vector addition is {arr1+arr2}")

Vector addition is [-51 -63 -62 -65 -71]


In [36]:
a1= np.random.randint(-1001,101, size=(5,5))
a2=np.random.randint(200,300, size=(5,5))
print(a1)
print(a2)
print(f"Vector sum of given vector is:\n {a1+a2}")

[[-402 -279 -223  -11 -441]
 [-723 -330   -8 -480 -617]
 [-673 -555 -539 -428 -591]
 [-845    6   59 -414  -49]
 [-553 -583 -840  -21 -614]]
[[258 292 211 234 245]
 [246 261 202 219 271]
 [249 285 207 288 236]
 [208 281 253 240 240]
 [264 218 256 262 229]]
Vector sum of given vector is:
 [[-144   13  -12  223 -196]
 [-477  -69  194 -261 -346]
 [-424 -270 -332 -140 -355]
 [-637  287  312 -174  191]
 [-289 -365 -584  241 -385]]


In [57]:
ar=[]
for i in range(25):
    ar.append(i)

a7=np.array(ar).reshape(5,5)
print(a7)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
